name: ecomtest
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^3.2.0
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  form_field_validator: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  injectable: ^2.4.2
  riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf